import type { Metadata } from "next";
import "@/styles/globals.css";
import { AuthProvider } from '@/context/auth-context';
// import { ChatProvider } from "@/context/chat-context";
import { Toaster } from 'sonner';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
