version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:7000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite_data:/app/prisma/data  # Mount point for SQLite database
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/prisma/data/dev.db  # SQLite connection string

volumes:
  sqlite_data: