version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://103.49.239.57:7000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite_data:/app/prisma/data
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/prisma/data/dev.db

volumes:
  sqlite_data: